In [1]:
import pandas as pd
df = pd.read_csv('Data/AppleStore.csv')
df.info()
df.head()
df2 = df.copy()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 17 columns):
Unnamed: 0          7197 non-null int64
id                  7197 non-null int64
track_name          7197 non-null object
size_bytes          7197 non-null int64
currency            7197 non-null object
price               7197 non-null float64
rating_count_tot    7197 non-null int64
rating_count_ver    7197 non-null int64
user_rating         7197 non-null float64
user_rating_ver     7197 non-null float64
ver                 7197 non-null object
cont_rating         7197 non-null object
prime_genre         7197 non-null object
sup_devices.num     7197 non-null int64
ipadSc_urls.num     7197 non-null int64
lang.num            7197 non-null int64
vpp_lic             7197 non-null int64
dtypes: float64(3), int64(9), object(5)
memory usage: 956.0+ KB

In [2]:
df.drop(['id'], axis = 1, inplace = True) # example data, 281656475
df.drop(['track_name'], axis = 1, inplace = True) #example data, PAC-MAN Premium 
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True) #example data, 1,2,3,4 numbering

In [3]:
df.head()

,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,100788224,USD,3.99,21292,26,4.0,4.5,6.3.5,4+,Games,38,5,10,1
1,158578688,USD,0.00,161065,26,4.0,3.5,8.2.2,4+,Productivity,37,5,23,1
2,100524032,USD,0.00,188583,2822,3.5,4.5,5.0.0,4+,Weather,37,5,3,1
3,128512000,USD,0.00,262241,649,4.0,4.5,5.10.0,12+,Shopping,37,5,9,1
4,92774400,USD,0.00,985920,5320,4.5,5.0,7.5.1,4+,Reference,37,5,45,1

In [4]:
df['user_rating_label'] = pd.cut(df['user_rating'], bins = 3, labels = ['Low', 'Medium', 'High'])
#df['user_rating_label'] = df['user_rating_label'].astype(str)
df.head(20)
#df[df['user_rating_label'].str.contains('High')].describe() #3.5 to 5.0
#df[df['user_rating_label'].str.contains('Medium')].describe() #2.0 to 3.0
#df[df['user_rating_label'].str.contains('Low')].describe() #0.0 to 1.5

,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic,user_rating_label
0,100788224,USD,3.99,21292,26,4.0,4.5,6.3.5,4+,Games,38,5,10,1,High
1,158578688,USD,0.00,161065,26,4.0,3.5,8.2.2,4+,Productivity,37,5,23,1,High
2,100524032,USD,0.00,188583,2822,3.5,4.5,5.0.0,4+,Weather,37,5,3,1,High
3,128512000,USD,0.00,262241,649,4.0,4.5,5.10.0,12+,Shopping,37,5,9,1,High
4,92774400,USD,0.00,985920,5320,4.5,5.0,7.5.1,4+,Reference,37,5,45,1,High
5,10485713,USD,0.99,8253,5516,4.0,4.0,1.8,4+,Games,47,5,1,1,High
6,227795968,USD,0.00,119487,879,4.0,4.5,6.12.0,4+,Finance,37,0,19,1,High
7,130242560,USD,0.00,1126879,3594,4.0,4.5,8.4.1,12+,Music,37,4,1,1,High
8,49250304,USD,9.99,1117,4,4.5,5.0,3.6.6,4+,Utilities,37,5,1,1,High
9,70023168,USD,3.99,7885,40,4.0,4.0,4.0.4,4+,Games,38,0,10,1,High
10,49618944,USD,4.99,76720,4017,4.5,4.5,4.10.1,4+,Games,38,4,11,1,High
11,227547136,USD,7.99,105776,166,3.5,2.5,5.19.0,4+,Games,37,0,6,1,High
12,179979264,USD,0.00,479440,203,3.5,4.0,27.0,17+,Utilities,37,4,33,1,High
13,160925696,USD,0.00,119773,2336,3.5,4.5,7.3.8,4+,Finance,37,0,2,1,High
14,55153664,USD,4.99,6340,668,4.5,4.5,4.0.3,4+,Games,38,5,2,1,High
15,207907840,USD,0.00,56194,87,4.0,3.5,21.1,4+,Travel,37,1,26,1,High
16,389879808,USD,0.00,2974676,212,3.5,3.5,95.0,4+,Social Networking,37,1,29,1,High
17,167407616,USD,0.00,223885,3726,4.0,4.5,11.15.0,12+,Travel,37,5,18,1,High
18,147093504,USD,0.00,402925,136,4.0,4.5,11.0.3,12+,Music,37,3,16,1,High
19,10735026,USD,2.99,31456,4178,4.0,3.5,1.0.0,4+,Games,47,0,1,1,High

In [5]:
df.drop(['user_rating'], axis = 1, inplace = True)
df.drop(['currency'], axis = 1, inplace = True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 13 columns):
size_bytes           7197 non-null int64
price                7197 non-null float64
rating_count_tot     7197 non-null int64
rating_count_ver     7197 non-null int64
user_rating_ver      7197 non-null float64
ver                  7197 non-null object
cont_rating          7197 non-null object
prime_genre          7197 non-null object
sup_devices.num      7197 non-null int64
ipadSc_urls.num      7197 non-null int64
lang.num             7197 non-null int64
vpp_lic              7197 non-null int64
user_rating_label    7197 non-null category
dtypes: category(1), float64(2), int64(7), object(3)
memory usage: 682.0+ KB

In [7]:
df.head(20)

,size_bytes,price,rating_count_tot,rating_count_ver,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic,user_rating_label
0,100788224,3.99,21292,26,4.5,6.3.5,4+,Games,38,5,10,1,High
1,158578688,0.00,161065,26,3.5,8.2.2,4+,Productivity,37,5,23,1,High
2,100524032,0.00,188583,2822,4.5,5.0.0,4+,Weather,37,5,3,1,High
3,128512000,0.00,262241,649,4.5,5.10.0,12+,Shopping,37,5,9,1,High
4,92774400,0.00,985920,5320,5.0,7.5.1,4+,Reference,37,5,45,1,High
5,10485713,0.99,8253,5516,4.0,1.8,4+,Games,47,5,1,1,High
6,227795968,0.00,119487,879,4.5,6.12.0,4+,Finance,37,0,19,1,High
7,130242560,0.00,1126879,3594,4.5,8.4.1,12+,Music,37,4,1,1,High
8,49250304,9.99,1117,4,5.0,3.6.6,4+,Utilities,37,5,1,1,High
9,70023168,3.99,7885,40,4.0,4.0.4,4+,Games,38,0,10,1,High
10,49618944,4.99,76720,4017,4.5,4.10.1,4+,Games,38,4,11,1,High
11,227547136,7.99,105776,166,2.5,5.19.0,4+,Games,37,0,6,1,High
12,179979264,0.00,479440,203,4.0,27.0,17+,Utilities,37,4,33,1,High
13,160925696,0.00,119773,2336,4.5,7.3.8,4+,Finance,37,0,2,1,High
14,55153664,4.99,6340,668,4.5,4.0.3,4+,Games,38,5,2,1,High
15,207907840,0.00,56194,87,3.5,21.1,4+,Travel,37,1,26,1,High
16,389879808,0.00,2974676,212,3.5,95.0,4+,Social Networking,37,1,29,1,High
17,167407616,0.00,223885,3726,4.5,11.15.0,12+,Travel,37,5,18,1,High
18,147093504,0.00,402925,136,4.5,11.0.3,12+,Music,37,3,16,1,High
19,10735026,2.99,31456,4178,3.5,1.0.0,4+,Games,47,0,1,1,High

In [8]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df['prime_genre'] = le.fit_transform(df['prime_genre'])
df['prime_genre'] = df['prime_genre'].astype(str)

In [9]:
#df['prime_genre2'] = le.fit_transform(df['prime_genre'])
#df['prime_genre'] = df['prime_genre'].astype(str)
#df.drop_duplicates(['prime_genre','prime_genre2'])[['prime_genre2','prime_genre']].sort_values(by=['prime_genre2']).style.hide_index()

newvalue	prime_genre<br>
0	Book<br>
1	Business<br>
2	Catalogs<br>
3	Education<br>
4	Entertainment<br>
5	Finance<br>
6	Food & Drink<br>
7	Games<br>
8	Health & Fitness<br>
9	Lifestyle<br>
10	Medical<br>
11	Music<br>
12	Navigation<br>
13	News<br>
14	Photo & Video<br>
15	Productivity<br>
16	Reference<br>
17	Shopping<br>
18	Social Networking<br>
19	Sports<br>
20	Travel<br>
21	Utilities<br>
22	Weather<br>

In [10]:
df['user_rating_label'] = le.fit_transform(df['user_rating_label'])
df['user_rating_label'] = df['user_rating_label'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 13 columns):
size_bytes           7197 non-null int64
price                7197 non-null float64
rating_count_tot     7197 non-null int64
rating_count_ver     7197 non-null int64
user_rating_ver      7197 non-null float64
ver                  7197 non-null object
cont_rating          7197 non-null object
prime_genre          7197 non-null object
sup_devices.num      7197 non-null int64
ipadSc_urls.num      7197 non-null int64
lang.num             7197 non-null int64
vpp_lic              7197 non-null int64
user_rating_label    7197 non-null object
dtypes: float64(2), int64(7), object(4)
memory usage: 731.1+ KB

In [11]:
df.head(10)

,size_bytes,price,rating_count_tot,rating_count_ver,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic,user_rating_label
0,100788224,3.99,21292,26,4.5,6.3.5,4+,7,38,5,10,1,0
1,158578688,0.00,161065,26,3.5,8.2.2,4+,15,37,5,23,1,0
2,100524032,0.00,188583,2822,4.5,5.0.0,4+,22,37,5,3,1,0
3,128512000,0.00,262241,649,4.5,5.10.0,12+,17,37,5,9,1,0
4,92774400,0.00,985920,5320,5.0,7.5.1,4+,16,37,5,45,1,0
5,10485713,0.99,8253,5516,4.0,1.8,4+,7,47,5,1,1,0
6,227795968,0.00,119487,879,4.5,6.12.0,4+,5,37,0,19,1,0
7,130242560,0.00,1126879,3594,4.5,8.4.1,12+,11,37,4,1,1,0
8,49250304,9.99,1117,4,5.0,3.6.6,4+,21,37,5,1,1,0
9,70023168,3.99,7885,40,4.0,4.0.4,4+,7,38,0,10,1,0

In [12]:
#df[df['user_rating_label'].str.contains('0')].describe() #3.5 to 5.0
#df[df['user_rating_label'].str.contains('0')] #High
#df[df['user_rating_label'].str.contains('1')].describe() #0.0 to 1.5 
#df[df['user_rating_label'].str.contains('1')] #Low
#df[df['user_rating_label'].str.contains('2')].describe() #2.0 to 3.0
#df[df['user_rating_label'].str.contains('2')] #Medium

#Average User Rating (for all version)
#user_rating_label: 0, 3.5 to 5.0 #High
#user_rating_label: 1, 0.0 to 1.5 #Low
#user_rating_label: 2, 2.0 to 3.0 #Medium


df['prime_genre'].describe()

count     7197
unique      23
top          7
freq      3862
Name: prime_genre, dtype: object

In [13]:
df['cont_rating'] = le.fit_transform(df['cont_rating'])
df['cont_rating'] = df['cont_rating'].astype(str)

#df['cont_rating2'] = le.fit_transform(df['cont_rating'])
#df['cont_rating'] = df['cont_rating'].astype(str)
#df.drop_duplicates(['cont_rating','cont_rating2'])[['cont_rating2','cont_rating']].sort_values(by=['cont_rating2']).style.hide_index()

In [14]:
#df.head(10)
#df.info()

cont_rating2	cont_rating<br>
0	12+<br>
1	17+<br>
2	4+<br>
3	9+<br>

In [15]:
df['ver'] = le.fit_transform(df['ver'])
df['ver'] = df['ver'].astype(str)

#df['ver2'] = le.fit_transform(df['ver'])
#df['ver'] = df['ver'].astype(str)
#df.drop_duplicates(['ver','ver2'])[['ver2','ver']].sort_values(by=['ver2']).style.hide_index()

ver got 0 to 1587 types of versions

# Experiment 1 (Lee Kar Choon)<br>
The choices of available machine learning algorithms are greatly dependent on the nature of a business problem. In this case, the original values of the attribute "user_rating" consist of a list of discrete values (ranging from 0 to 5), it will be difficult to apply a regression algorithm for the prediction task, since it may yield a predicted outcome beyond the range of rating value. This problem can be framed as a multiclass classification problem and data preprocessing will be conducted to group several discrete values into the same class to simplify the prediction task. A few choices of machine learning algorithms specialized for classification task as below will be studied: K-Nearest Neighbors (KNN), Decision Tree and Support Vector Machine (SVM). Then, the recursive process of training and fine-tuning parameters of the machine learning model built from each of these 3 algorithms will be conducted. Finally, the machine learning algorithm that yields the best performing classification model will be identified and further investigated.

In [16]:
# Indicate the target column
target = df['user_rating_label']
features = df.drop('user_rating_label', axis = 1)
#features = df.drop(['user_rating_label','ver'], axis = 1)
#target.head(10) #more grouping result
#features.head(10) #more grouping result
#target.tail(30) #more random result
#features.tail(30) #more random result

In [17]:
target.value_counts()

0    5483
1    1029
2     685
Name: user_rating_label, dtype: int64

In [18]:
# Import train_test_split function 
# Import function for k-fold cross validation
# Import scikit-Learn metrics module for accuracy calculation
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

# Split data into train, validation and test sets
x_train, x_test, y_train, y_test = train_test_split(features, target, \
                                                   test_size = 0.2, random_state =0)

#K-Nearest Neighbors (KNN)
from sklearn.neighbors import KNeighborsClassifier
# Create a KNN classifier with k = 5 
knn = KNeighborsClassifier(n_neighbors = 3)
scores = cross_val_score(knn, x_train, y_train, cv = 10, scoring = 'f1_macro')

knn.fit(x_train, y_train)
# Predict the target for the test dataset
test_predict = knn.predict(x_test)
# Display the array containing accuracy from 10 folds or iterations
# Print the mean accuracy score
# Compute the model accuracy on the test set
print(scores)
print('fl_macro (Validation) = ', scores.mean())
print('fl_macro (test): ',  metrics.f1_score(y_test, test_predict, average = 'macro'))
#print('Accuracy (test): ',  metrics.accuracy_score(y_test, test_predict))
# Print confusion matrix 
print(confusion_matrix(y_test, test_predict))
# Print precision, recall and F1 
print(classification_report(y_test, test_predict))

#param_norm_knn = {'n_neighbors': range(1,10),
#             'weights': ['uniform','distance'],
#             'p': [1,2] }

[0.32108118 0.31708412 0.35302573 0.3409604  0.32512096 0.34739571
 0.32942628 0.34551382 0.3409883  0.37393457]
fl_macro (Validation) =  0.3394531049071421
fl_macro (test):  0.34235527231968366
[[1017   54   31]
 [ 162   18    9]
 [ 137    7    5]]
              precision    recall  f1-score   support

           0       0.77      0.92      0.84      1102
           1       0.23      0.10      0.13       189
           2       0.11      0.03      0.05       149

    accuracy                           0.72      1440
   macro avg       0.37      0.35      0.34      1440
weighted avg       0.63      0.72      0.67      1440

In [19]:
# Try KNN standardized
from sklearn import preprocessing

names = features.columns

# Create the Scaler object
scaler = preprocessing.StandardScaler()
scaled_features = scaler.fit_transform(features)
scaled_features = pd.DataFrame(scaled_features, columns = names)
scaled_features.head()

,size_bytes,price,rating_count_tot,rating_count_ver,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,-0.273806,0.388126,0.110902,-0.110805,0.688921,1.967780,0.303584,-0.324940,0.170753,0.651051,0.576471,0.083642
1,-0.112911,-0.295960,1.956477,-0.110805,0.136202,2.278879,0.303584,1.319353,-0.096808,0.651051,2.218083,0.083642
2,-0.274542,-0.295960,2.319827,0.602428,0.688921,1.578329,0.303584,2.758109,-0.096808,0.651051,-0.307474,0.083642
3,-0.196620,-0.295960,3.292413,0.048117,0.688921,1.638245,-1.943092,1.730426,-0.096808,0.651051,0.450193,0.083642
4,-0.296117,-0.295960,12.847931,1.239643,0.965281,2.182093,0.303584,1.524889,-0.096808,0.651051,4.996197,0.083642

In [20]:
# Split data into train, validation and test sets
scaled_x_train, scaled_x_test, scaled_y_train, scaled_y_test = train_test_split(scaled_features, target, \
                                                   test_size = 0.2, random_state =0)
knn = KNeighborsClassifier(n_neighbors = 3)
scores = cross_val_score(knn, scaled_x_train, scaled_y_train, cv = 10, scoring = 'f1_macro')

knn.fit(scaled_x_train, scaled_y_train)
# Predict the target for the test dataset
test_predict = knn.predict(scaled_x_test)
# Display the array containing accuracy from 10 folds or iterations
# Print the mean accuracy score
# Compute the model accuracy on the test set
print(scores)
print('fl_macro (Validation) = ', scores.mean())
print('fl_macro (test): ',  metrics.f1_score(scaled_y_test, test_predict, average = 'macro'))
#print('Accuracy (test): ',  metrics.accuracy_score(y_test, test_predict))
# Print confusion matrix 
print(confusion_matrix(scaled_y_test, test_predict))
# Print precision, recall and F1 
print(classification_report(scaled_y_test, test_predict))

[0.66347055 0.61975152 0.63262671 0.64661993 0.63972597 0.7006876
 0.68371685 0.64576695 0.69652364 0.66649018]
fl_macro (Validation) =  0.6595379907800879
fl_macro (test):  0.690427382576512
[[1026   43   33]
 [  31  157    1]
 [  92   14   43]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      1102
           1       0.73      0.83      0.78       189
           2       0.56      0.29      0.38       149

    accuracy                           0.85      1440
   macro avg       0.73      0.68      0.69      1440
weighted avg       0.84      0.85      0.84      1440

In [21]:
# Import GridSearch from the sklearn library
from sklearn.model_selection import GridSearchCV

# Thep param_grid specifies one grid should be explored
param_grid = {'n_neighbors' : range(2,20)}

# Fit on the dataset on all parameter combinations in param_grid
# Retain the best combination
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv = 10, scoring = 'f1_macro') #f1_macro
grid_result = grid_search.fit(x_train, y_train)
grid_result.best_params_
#f1_macro: 3
#f1_weighted: 10
#accuracy: 18

{'n_neighbors': 3}

In [22]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(criterion = 'gini',splitter = 'best', random_state = 0)
scores = cross_val_score(dtree, x_train, y_train, cv = 10, scoring = 'f1_macro')

dtree.fit(x_train, y_train)
# Predict the target for the test dataset
test_predict = dtree.predict(x_test)
# Display the array containing accuracy from 10 folds or iterations
# Print the mean accuracy score
# Compute the model accuracy on the test set
print(scores)
print('fl_macro (Validation) = ', scores.mean())
print('fl_macro (test): ',  metrics.f1_score(y_test, test_predict, average = 'macro'))
#print('Accuracy (test): ',  metrics.accuracy_score(y_test, test_predict))
# Print confusion matrix 
print(confusion_matrix(y_test, test_predict))
# Print precision, recall and F1 
print(classification_report(y_test, test_predict))

[0.74815028 0.80630363 0.7825534  0.80140967 0.77673852 0.77942393
 0.7733649  0.75746757 0.75274588 0.78619083]
fl_macro (Validation) =  0.7764348616839338
fl_macro (test):  0.7732013528151364
[[1025   15   62]
 [   4  180    5]
 [  77    6   66]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      1102
           1       0.90      0.95      0.92       189
           2       0.50      0.44      0.47       149

    accuracy                           0.88      1440
   macro avg       0.77      0.78      0.77      1440
weighted avg       0.88      0.88      0.88      1440

In [101]:
# Thep param_grid specifies one grid should be explored
param_grid = {'criterion' : ['gini','entropy'],
                    'splitter' : ['best','random']}
# Fit on the dataset on all parameter combinations in param_grid
# Retain the best combination
grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid, cv = 10, scoring = 'f1_macro') #f1_macro
grid_result = grid_search.fit(x_train, y_train)
grid_result.best_params_

{'criterion': 'gini', 'splitter': 'best'}

In [ ]:
# mport SVM classifier
from sklearn.svm import SVC
#SVM (Linear)
svmlinear = SVC(kernel = 'linear')
scores = cross_val_score(svmlinear, x_train, y_train, cv = 10, scoring = 'f1_macro')
#svmlinear.fit(x_train, y_train)
# Predict the target for the test dataset
#test_predict = svmlinear.predict(x_test)
# Display the array containing accuracy from 10 folds or iterations
# Print the mean accuracy score
# Compute the model accuracy on the test set
print(scores)
print('fl_macro (Validation) = ', scores.mean())
#print('fl_macro (test): ',  metrics.f1_score(y_test, test_predict, average = 'macro'))
## Print confusion matrix 
#print(confusion_matrix(y_test, test_predict))
## Print precision, recall and F1 
#print(classification_report(y_test, test_predict))